---
title: "main"
author: "Xiaomeng Liu"
date: "2024-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(caret)
library(tidyverse)
library(randomForest)
```


1. Read in data
```{r}
test<-read.csv("Assignment_Test.csv")
train<-read.csv("Assignment_train.csv")
```

```{r}
ls(train,sorted = FALSE)
```

2.data validation and cleaning

```{r}
train_mod<-train[,c(9,10,11,12,13,14,16,17,18,20,21,22,23,24,27)]
train_mod<-cbind(train_mod,train[,32:55])
# 39 variables left after this modification
train_mod<-train_mod[,c(-16,-22,-23,-25,-27,-29,-33,-34)]
train_mod<-train_mod[train_mod$EMPLOYER.TYPE != "",]
train_mod<-train_mod[train_mod$phone_phoneFootprintStrengthOverall != "",]
train_mod<-train_mod[train_mod$ADDRESS.TYPE != "",]
```

```{r}
str(train_mod)
summary(train_mod)
```

Convert character vars to factor
```{r}
facnum<-c(1,3,4,6,8,9,10,11,12,14,15,30,31)
train_mod[,facnum]<-lapply(train_mod[,facnum],factor)
train_mod[,16:27]<-lapply(train_mod[,c(16:27)],factor)
train_mod[,2]<-as.numeric(train_mod[,2])
str(train_mod)
```
```{r,eval=FALSE}
#train_mod <-tibble(train_mod)
#train_mod<-train_mod %>% drop_na() 
# remove null values will cause the response to be single value
#str(train_mod)
train_mod[is.na(train_mod)]<-0
```

```{r}
#column1 and 3 has only 1 level so drop it
train_mod<-train_mod[,c(-1,-3,-4,-6,-8,-9,-12)]


#remove dealer name to check whether it works
str(train_mod)
```


3. Generate Model Based on Training Set

```{r}
model1<-glm(Application.Status~.,data = train_mod,family = "binomial")
summary(model1)
```


```{r}
# second attempt
model2<-train(Application.Status~.,data=train_mod,method="glm",
              #metric="logloss",
              #trCrontrol=trainControl(method="cv",number = 5, classProbs = TRUE,
                                      #summaryFunction = mnLogLoss),
              preProcess=c("center","scale")
              )
summary(model2)
```

4. Make the prediction

```{r}
testresult<-predict(model2,data = test)
unique(testresult)
```
